Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 12
Style/DoubleNegation:
  Enabled: false